email: email@domain.com
password: mypassword
bookingDay: 1 # how many days in advance, put 3 if you are running it the night before via a cronjob
bookingTime: 7:00 PM # Must be exact, in hh:MM AM/PM format
club:
  useClubName: False # Set to True to change to this club
  clubName: Waterloo Erb Street # Exact name of the club as on the club selection list