email: email@domain.com
password: mypassword
bookingDay: 3 # how many days in advance, put 3 if you are running it the night before via a cronjob
bookingTimes:
 Monday: 7:00 PM
 Tuesday: 7:00 PM
 Wednesday: None
 Thursday: 7:00 PM
 Friday: 7:00 PM
 Saturday: None
 Sunday: None
club:
  useClubName: False
  clubName: Waterloo Erb Street